# Generated by Django 5.1.4 on 2025-01-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
