# Generated by Django 5.1.4 on 2025-01-14 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_rename_is_canceled_agendamento_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='is_deleted',
            new_name='deletado',
        ),
    ]
